---
title: "Abstract 1 Data Analysis"
author:
  - "Pol Castellano-Escuder"
date: "`r format(Sys.time(), '%d %b, %Y')`"
output: pdf_document
---

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
library(tidyverse)

data <- readxl::read_xlsx("xxxx")

data_subset <- data %>%
  janitor::clean_names() %>% # clean column names
  select_if(~ sum(!is.na(.)) > 0) %>% # drop columns that only have NAs
  mutate_at(vars(tidyr::starts_with("tn_")), ~ as.numeric(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("n_")), ~ as.numeric(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("f_")), ~ as.factor(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("c_")), as.character) %>%
  mutate_at(vars(tidyr::starts_with("id_")), as.character) %>%
  rename_at(vars(contains("date")), ~ "date") %>% # modify var name
  rename_at(vars(tidyr::starts_with("id_")), ~ "id") %>% # modify var name
  select_if(~ !(sum(is.na(.))/nrow(data))*100 > 20) %>% # remove na
  mutate_at(vars(tidyr::starts_with("tn_")), function(x)ifelse(x == 0, 0.01, x)) %>% # replace zeros
  mutate_at(vars(tidyr::starts_with("tn_")), log10) %>% # log10 transformation
  rename_at(vars(tidyr::starts_with("tn_")), ~ paste0(., "_log10")) %>% # modify log10 transformed var names
  dplyr::select(id, date, everything()) 

data_subset <- data_subset %>%
  filter(f_outcome_final %in% c("HOME", "EXITUS"))

data_subset <- data_subset[ -as.numeric(which(apply(data_subset, 2, var) == 0))] # remove 0 var columns
```

## Linear Model: UREA-EDAD

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
summary(lm(n_age_years ~ n_urea_f, data = data_subset))

ggplot(data_subset, aes(n_age_years, n_urea_f)) +
  geom_point() +
  ylab("Urea") +
  xlab("Age") + 
  geom_smooth(method = "lm") + 
  geom_text(aes(25, 300, label = paste0("R = ", round(cor(n_age_years, n_urea_f, use = "pairwise.complete.obs"), 2))), check_overlap = TRUE) +
  theme_bw()
```

## ttest

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
data_numeric <- data_subset %>%
  select_at(vars(contains("outcome") | starts_with("n_") | starts_with("tn_")))

## means and sds

mean_group <- data_numeric %>% 
  group_by(f_outcome_final) %>% 
  summarise(across(
    .cols = is.numeric, 
    .fns = list(mean = mean), na.rm = TRUE, 
    .names = "{col}"
  )) %>%
  ungroup() %>%
  column_to_rownames("f_outcome_final") %>%
  t() %>%
  as_tibble()

sd_group <- data_numeric %>% 
  group_by(f_outcome_final) %>% 
  summarise(across(
    .cols = is.numeric, 
    .fns = list(sd = sd), na.rm = TRUE, 
    .names = "{col}"
  )) %>%
  ungroup() %>%
  column_to_rownames("f_outcome_final") %>%
  t() %>%
  as_tibble()

mean_sd <- round(cbind(mean_group, sd_group), 2) %>%
  rename(mean_exitus = 1, mean_home = 2, sd_exitus = 3, sd_home = 4)

## tests

Group <- data_numeric %>%
  select(f_outcome_final) %>%
  pull()

data_numeric <- data_numeric %>%
  select(-f_outcome_final)

stat <- function(x) {t.test(x ~ Group, na.rm = TRUE, alternative = c("two.sided"), var.equal = FALSE, paired = FALSE)$p.value}

p <- data.frame(pvalue = apply(FUN = stat, MARGIN = 2, X = data_numeric))
p <- p %>% 
  rownames_to_column("ID") %>% 
  mutate(pvalueAdj = p.adjust(pvalue, method = "fdr")) %>% 
  column_to_rownames("ID")

p <- bind_cols(mean_sd, p) %>% 
  rownames_to_column("feature") %>%
  arrange(-desc(pvalueAdj))

knitr::kable(p, format = "latex")
```

