---
title: "Representative Samples to Analyze more Cytokines"
author:
  - "Pol Castellano-Escuder"
  - "Paco Carmona-Pontaque"
  - "Alex Sánchez-Pla"
date: "`r format(Sys.time(), '%d %b, %Y')`"
output: pdf_document
---

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
library(tidyverse)

data <- readxl::read_xlsx("~/abstract_1/ok/2020 07 14 Day_one_1802.xlsx")

data_subset <- data %>%
  janitor::clean_names() %>% # clean column names
  select_if(~ sum(!is.na(.)) > 0) %>% # drop columns that only have NAs
  mutate_at(vars(tidyr::starts_with("tn_")), ~ as.numeric(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("n_")), ~ as.numeric(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("f_")), ~ as.factor(as.character(.))) %>%
  mutate_at(vars(tidyr::starts_with("c_")), as.character) %>%
  mutate_at(vars(tidyr::starts_with("id_")), as.character) %>%
  rename_at(vars(contains("date")), ~ "date") %>% # modify var name
  rename_at(vars(tidyr::starts_with("id_")), ~ "id") %>% # modify var name
  select_if(~ !(sum(is.na(.))/nrow(data))*100 > 20) %>% # remove na
  mutate_at(vars(tidyr::starts_with("tn_")), function(x)ifelse(x == 0, 0.01, x)) %>% # replace zeros
  mutate_at(vars(tidyr::starts_with("tn_")), log10) %>% # log10 transformation
  rename_at(vars(tidyr::starts_with("tn_")), ~ paste0(., "_log10")) %>% # modify log10 transformed var names
  dplyr::select(id, date, everything()) %>%
  filter(f_outcome_final %in% c("HOME", "EXITUS")) %>%
  mutate(n_age_interval = ifelse(n_age_years > 80, ">80", 
                                 ifelse(n_age_years > 65 & n_age_years <= 80, "66-80",
                                        ifelse(n_age_years > 50 & n_age_years <= 65, "51-66",
                                               ifelse(n_age_years > 25 & n_age_years <= 50, "26-50",
                                                 ifelse(n_age_years > 5 & n_age_years <= 25, "6-25", "0-5"))))),
         na_row_pc = (rowSums(is.na(.))/ncol(.)) * 100) %>%
  filter(na_row_pc <= 20)

data_subset <- data_subset[, -as.numeric(which(apply(data_subset, 2, var) == 0))] # remove 0 var columns
```

## All Data (`r nrow(data_subset)` samples)

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
ggplot(data_subset, aes(f_outcome_final, fill = n_age_interval)) +
  geom_bar(stat = "count") +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(legend.title = element_blank()) +
  viridis::scale_fill_viridis(discrete = TRUE)
```

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
# Create new data

n_max <- 90

data_subset2 <- data_subset %>%
  mutate(strata = as.factor(paste0(n_age_interval, "_" , f_outcome_final)))
        
strata_prop <- table(data_subset2$strata)/sum(table(data_subset2$strata)) * n_max

sst <- list()
for(i in 1:length(strata_prop)){
  data_sub <- data_subset2[data_subset2$strata == names(strata_prop[i]) ,]
  
  idx <- sample(nrow(data_sub), strata_prop[i], replace = FALSE)
  sst[[i]] <- data_sub[idx,]
}

new_data <- bind_rows(sst)
openxlsx::write.xlsx(new_data, file = "new_data.xlsx", row.names = FALSE)
```

## New Data (`r nrow(new_data)` samples)

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
ggplot(new_data, aes(f_outcome_final, fill = n_age_interval)) +
  geom_bar(stat = "count") +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(legend.title = element_blank()) +
  viridis::scale_fill_viridis(discrete = TRUE)
```

## Outlier Check

```{r, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
library(vegan)

coef <- 1.5

groups <- new_data$strata
names <- new_data$id
to_outliers <- new_data %>%
  select_at(vars(starts_with("n_") | starts_with("tn_")))

dd <- dist(to_outliers, method = "euclidean")
distances <- vegan::betadisper(dd, groups, type = "median", bias.adjust = FALSE, sqrt.dist = FALSE, add = FALSE)
detect_outliers <- data.frame(distances = distances$distances, Groups = distances$group)
limit <- data.frame(aggregate(detect_outliers$distances, 
                              list(detect_outliers$Groups), 
                              function(x) {quantile(x, 0.75) + coef * IQR(x)}))
colnames(limit)[1] <- "Groups"
detect_outliers <- merge(detect_outliers, limit, by = "Groups")
detect_outliers <- detect_outliers %>% 
  mutate(out = as.factor(ifelse(distances > x, 1, 0)), sample = names)

final_outliers <- detect_outliers %>% filter(out == 1) %>% 
  select(sample, Groups, distances, x) %>% 
  rename(group = Groups, distance_to_centroid = distances, limit_distance = x)

vectors <- data.frame(distances$vectors)
centroids <- data.frame(distances$centroids)
total_outliers <- vectors %>% 
  mutate(Group = groups)

find_hull <- function(x) {x[chull(x$PCoA1, x$PCoA2), ]}

hulls <- total_outliers %>% 
  group_by(Group) %>% 
  dplyr::do(find_hull(.))

ggplot(total_outliers, aes(x = PCoA1,  y = PCoA2)) + 
  geom_polygon(data = hulls, alpha = 0.5, aes(fill = Group)) + 
  geom_point(aes(shape = Group), size = 3, alpha = 0.7) + 
  geom_label(data = centroids, aes(x = PCoA1, y = PCoA2, label = rownames(centroids)), show.legend = FALSE) + 
  theme_bw()

ggplot(detect_outliers, aes(Groups, distances, fill = Groups)) + 
  geom_boxplot(coef = coef, alpha = 0.8) + 
  ylab("Distance to group centroid") + 
  xlab("") + 
  ggrepel::geom_label_repel(data = detect_outliers[detect_outliers$out == 1 ,], aes(label = sample), na.rm = TRUE, size = 4, show.legend = FALSE) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

